GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/5f02f611174f8e1bfa061c0d
###
DELETE  http://localhost:3001/api/persons/5f02f611174f8e1bfa061c0d
###
GET http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "rmasd",
  "number": "19288"
}
###
PUT http://localhost:3001/api/persons/5f02f611174f8e1bfa061c0d
Content-Type: application/json

{
  "number": 23451235
}
