GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/3
###
DELETE  http://localhost:3001/api/persons/3
###
GET http://localhost:3001/api/persons/3
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "random",
  "number": "199099288"
}
